src/notebook_unit1.ipynb
* read and display expec.t
* eliminate columns based on variance
=> Notebook Unit 1 - Statistical task 1

src/notebook_unit1.ipynb
* plotting of the data in expec.t: Plotting the variables <z> and <H> against time
* saving the plot as pdf
=> Notebook Unit 1 - Statistical task 2

src/notebook_unit1.ipynb
* read `npop.t`
* discard columns with low variance
* plot the data using seaborn
* investigate correlations in the data
=> Notebook Unit 1 - Statistical task 3

src/notebook_unit1.ipynb
* calculate Euclidean distances between vector pairs in `table.dat`
* plot the distances as histogram
* save the distances to file
=> Notebook Unit 1 - Statistical task 5

src/notebook_unit1.ipynb
Deleted comment line. Please can someone check my pull request.
=> updated notebook

.pre-commit-config.yaml, src/notebook_unit1.ipynb
* added linting to pre-commit hooks
* reformatted jupyter notebook accordingly
=> Unit2 linting

src/oop_analysis.py
* Implement calculation and processing of correlation matrix
* add type hints
* add docstring (reStructuredText format)
closes #18
=> Corr matrix

docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/index.rst, docs/source/license.md, docs/source/modules.rst, docs/source/oop_analysis.rst, docs/source/readme.md, docs/source/test.rst
* add docs and docs/source directories with files
* add some first pages: readme, modules, license
=> add initial documentation files for sphinx

.gitattributes, conda_env.yml, requirements.txt
- added .gitattributes file
- added conda .yml file and requirements.txt (incl. sphinx)
=> A bit of preparation for unit 4

docs/source/index.rst, docs/source/requirements_link.rst
add Requirements page with reference to requirements.txt
=> add Requirements page to documentation

src/oop_analysis.py
- Implemented issues 16 and 19.
- Added suggestion for how to handle user input (currently commented out)
Closed issues:
- Closes #16 
- Closes #19
=> implemented issues 16 and 19

.flake8, src/oop_analysis.py, src/test_oop_analysis.py
* slightly modified correlation function
* renamed correlation function from `create_corr_matrix()` to `get_corr()`
* add unit test for correlation function
* edited .flake8 --> @vivienzahs @rdlaura Run `pre-commit install` to apply changes on your local machine
=> Unittest for corr function

src/test_oop_analysis.py
- Added a script for unit tests (relevant for unit 5) which contains a test function for method "read_csv_as_df" of class "in_out". Script can be extended by further test functions.
- Modified method "read_csv_af_df" due to errors in reading input
- Modified return of several methods so attributes of objects of this class as actually assigned the value of the return.
=> commited test script with unittest for import of csv file

src/pytest.ini
=> added pytest.ini file

src/oop_analysis.py
* make sure that formatting is correct and pre-commit hooks run through
* fixed small issue in variance filter function --> assignment to `self.df_clean` instead of `df_clean`
=> some reformatting, small fix in variance filter

src/oop_analysis.py, src/test/test_oop_analysis.py
* move test directory to `src` folder and rename to `test`
* fix `test_get_corr()`
=> revision of tests

src/notebook_unit1.ipynb
Implement autocorrelation function
=> Numerical analysis Task 3

src/test/test_oop_analysis.py
fixed bug, tests should now pass.
=> fixed bug in test function test_read_csv_as_df

.github/workflows/main.yml, requirements.txt
add CI workflow and update requirements
=> Add workflow

src/test/test_oop_analysis.py
=> changed slashes in filename
